parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: dov--nmr

    mailer_transport:  smtp
    mailer_host:       smtp.gmail.com
    mailer_user:       FxGarantServer
    mailer_password:   fx-gr-sr
    mailer_port:       465
#    mailer_host:       127.0.0.1
#    mailer_user:       dovnmr
#    mailer_password:   dov--nmr
#    mailer_port:       25
    
    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
